@baseUrl = http://localhost/order
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4Y2NlOWUwYy00OWFkLTQ5YzUtOGI3Mi1iNmFjMzRkZGI0MGQiLCJlbWFpbCI6ImpvYW8uc2lsdmFAZW1haWwuY29tIiwicm9sZSI6IkNVU1RPTUVSIiwiZmlyc3ROYW1lIjoiSm_Do28iLCJsYXN0TmFtZSI6IlNpbHZhIiwiaWF0IjoxNzMzNjI2Njk2LCJleHAiOjE3MzM3MTMwOTZ9.-RvLm36p8tJ9h5SH3tWoPwm_BiI2UQe5XEn8DuqLNj0

### Health Check
GET {{baseUrl}}/health

### Create Order
POST {{baseUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId": "123e4567-e89b-12d3-a456-426614174000",
  "pickupAddressId": "22f8bc6c-f8c6-4232-84da-943aac48eb23",
  "deliveryAddressId": "22f8bc6c-f8c6-4232-84da-943aac48eb23",
  "transportType": "GROUND"
}

### Get Order by ID
GET {{baseUrl}}/6e3b7504-0c21-4300-8a9f-7f26b4b303be
Authorization: Bearer {{token}}

### Update Order
PUT {{baseUrl}}/6e3b7504-0c21-4300-8a9f-7f26b4b303be
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "status": "IN_TRANSIT",
  "estimatedDeliveryDate": "2024-03-20T15:00:00Z"
}

### Cancel Order
DELETE {{baseUrl}}/123e4567-e89b-12d3-a456-426614174003
Authorization: Bearer {{token}}

### List User Orders
GET {{baseUrl}}/user/123e4567-e89b-12d3-a456-426614174000
Authorization: Bearer {{token}}
