apiVersion: v1
kind: Pod
metadata:
  name: test-rabbitmq-amqp
  namespace: dropp
spec:
  restartPolicy: Never
  containers:
  - name: amqp-test
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
      - |
        apt-get update && apt-get install -y amqp-tools
        amqp-declare-queue --url=amqp://user:password@rabbitmq:5672 -q test_queue
