apiVersion: v1
kind: Pod
metadata:
  name: test-rabbitmq
  namespace: dropp
spec:
  restartPolicy: Never
  containers:
  - name: amqp-test
    image: alpine
    command: ["/bin/sh", "-c"]
    args:
      - |
        apk add --no-cache netcat-openbsd
        nc -zv rabbitmq 5672
