apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: dropp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: oven/bun:latest
          workingDir: /app
          command: ['sh', '-c']
          args: ['bun install && bun run db:wait && bun run dev']
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: '3000'
            - name: DATABASE_URL
              value: 'postgres://user:password@postgres:5432/payment_db'
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: RABBITMQ_URL
              value: 'amqp://user:password@rabbitmq:5672'
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBITMQ_PASSWORD
            - name: EUPAGO_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: EUPAGO_API_KEY
            - name: EUPAGO_BASE_URL
              value: 'https://sandbox.eupago.pt/'
          volumeMounts:
            - name: app-code
              mountPath: /app
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10
      volumes:
        - name: app-code
          hostPath:
            path: /Users/vhugo/IPCA/2024/MEI/Projeto de Computação na Cloud /app/payment
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: dropp
spec:
  selector:
    app: payment
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
